//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroPicker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeroPicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Though the travelers and road trippers who used to cross the US on historic 
        ///Route 66 are gone, the Main Street of America still stands, a testament to a 
        ///simpler time. The gas stations, roadside shops, and cafes have gone into disuse, 
        ///and the fabled Deadlock Gorge is mostly seen from the comfort of transcontinental 
        ///train cars. But amid the fading monuments of that earlier era, the outlaws of the 
        ///Deadlock Gang are planning their biggest heist yet..
        /// </summary>
        internal static string _66 {
            get {
                return ResourceManager.GetString("_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ana {
            get {
                object obj = ResourceManager.GetObject("Ana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana&apos;s versatile arsenal allows her to affect heroes all over the
        /// battlefield. Her Biotic Rifle rounds and Biotic Grenades heal 
        ///allies and damage or impair enemies; her sidearm tranquilizes 
        ///key targets, and Nano Boost gives one of her comrades a considerable 
        ///increase in power. .
        /// </summary>
        internal static string Ana1 {
            get {
                return ResourceManager.GetString("Ana1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Anubis {
            get {
                object obj = ResourceManager.GetObject("Anubis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Arcade is a play mode in Overwatch. It features a rotating variety of exclusive game modes, maps, and rulesets. Players can earn Loot Boxes by winning games, and earn the same amount of experience that is available in Quick Play.
        ///
        ///.
        /// </summary>
        internal static string Arcade {
            get {
                return ResourceManager.GetString("Arcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault, sometimes referred to as Two Capture Point (2CP) , is a Game Mode in which the attacking and defending teams must attempt to take or defend capture points across the map. Defenders always have the same spawnpoint, whether defending the first or second point, while the attacker&apos;s spawn changes depending on the point they are attempting to capture. It should be noted that every Assault map has an almost-immediate choke point, and that the defenders&apos; spawn is just behind the second point, making the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Assault {
            get {
                return ResourceManager.GetString("Assault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid (also known as Assault/Escort) is a combination of the game modes Assault and Escort. It is one of the 4 main gamemodes in Overwatch..
        /// </summary>
        internal static string Assault_Escort {
            get {
                return ResourceManager.GetString("Assault_Escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bastion {
            get {
                object obj = ResourceManager.GetObject("Bastion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair protocols and the ability to transform between stationary Assault, 
        ///mobile Recon and devastating Tank configurations provide Bastion with a 
        ///high probability of victory. .
        /// </summary>
        internal static string Bastion1 {
            get {
                return ResourceManager.GetString("Bastion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black {
            get {
                object obj = ResourceManager.GetObject("Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blizzard Entertainment, Inc. is an American 
        ///video game developer and publisher based in 
        ///Irvine,California, and is a subsidiary of the 
        ///American company Activision Blizzard..
        /// </summary>
        internal static string Blizzard_exp {
            get {
                return ResourceManager.GetString("Blizzard_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castillo is an old fort looking out over Dorado&apos;s bay. It’s the location of Calaveras, a bar frequented by questionable patrons; a graffitied Los Muertos hangout; and Sombra&apos;s hacking den..
        /// </summary>
        internal static string Casti {
            get {
                return ResourceManager.GetString("Casti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Castillo {
            get {
                object obj = ResourceManager.GetObject("Castillo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Chateau_Guillard {
            get {
                object obj = ResourceManager.GetObject("Chateau_Guillard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Control, two teams fight over a series of objective areas in a best-of-three format. This means that there is no distinction to attacking or defending teams like in other game modes.
        ///
        ///Each of the Control maps has three objective areas, randomly chosen for every round..
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap D_Va {
            get {
                object obj = ResourceManager.GetObject("D_Va", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.Va’s mech is nimble and powerful — its twin Fusion Cannons blast 
        ///away with autofire at short range, and she can use its Boosters to 
        ///barrel over enemies and obstacles, or absorb attacks with her 
        ///projectile-dismantling Defense Matrix. .
        /// </summary>
        internal static string D_Va1 {
            get {
                return ResourceManager.GetString("D_Va1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense heroes are good at guarding locations, creating choke points, and preventing objectives from being taken.
        ///They are skilled at area denial and generally form the back line of their team. .
        /// </summary>
        internal static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Doomfist {
            get {
                object obj = ResourceManager.GetObject("Doomfist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doomfist’s cybernetics make him a highly-mobile, powerful frontline fighter. In addition to dealing ranged damage with his Hand Cannon, Doomfist can slam the ground, knock enemies into the air and off balance, or charge into the fray with his Rocket Punch. When facing a tightly packed group, Doomfist leaps out of view, then crashes down to earth with a spectacular Meteor Strike..
        /// </summary>
        internal static string Doomfist1 {
            get {
                return ResourceManager.GetString("Doomfist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dorado {
            get {
                object obj = ResourceManager.GetObject("Dorado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eco {
            get {
                object obj = ResourceManager.GetObject("Eco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintained by Overwatch, the ecopoint served as a monitoring station for the study of Earth&apos;s changing climate.
        ///
        ///Disaster struck the station when it was hit by a polar storm, damaging the station&apos;s solar array. Cut off from the outside world, the scientists were left stranded in the damaged facility. As their supplies dwindled, they entered cryostasis in a last-ditch effort to survive until a rescue attempt could be made.
        ///
        ///Rescue came years later, but Dr. Mei-Ling Zhou was the only survivor. By this poi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ecopoint {
            get {
                return ResourceManager.GetString("Ecopoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The town was the site of one of the most famous 
        ///battles during the Omnic Crisis. It was here that 
        ///the leader of the Crusaders, Balderich von Adler, 
        ///and a handful of his best soldiers, including his pupil, 
        ///Reinhardt Wilhelm, made a last stand against an advancing automaton army.
        ///Since Eichenwalde was in the way of a larger omnic advance to Stuttgart, 
        ///the town was evacuated on October 11, from 3 to 8 o&apos;clock. Outnumbered and outgunned, 
        ///almost all Crusaders were slain during the resulting combat,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eiche {
            get {
                return ResourceManager.GetString("Eiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eichenwalde {
            get {
                object obj = ResourceManager.GetObject("Eichenwalde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is Festival de la Luz in Dorado, an annual celebration of the end of the Omnic Crisis 
        ///and the period of darkness – both figurative and literal – that engulfed Mexico when the 
        ///omnics destroyed much of the country’s power grid and infrastructure. But there is a new 
        ///dawn, as LumériCo and its CEO, war hero and former president Guillermo Portero, are 
        ///unveiling a string of fusion plants that promise to deliver clean, free energy to the Mexican people.
        ///.
        /// </summary>
        internal static string El_dorado {
            get {
                return ResourceManager.GetString("El_dorado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Escort, there is an attacking and a defending team. Teams&apos; roles are determined randomly when the map is chosen, and once the match is complete, roles are swapped.
        ///
        ///The attacking team aims to escort a payload across the map to the objective, while the defending team aims to stop them.
        ///
        ///At the start of each round, the defending team is allocated some time to set up defenses before the attacking team is allowed out of their spawn area. When the set up timer runs out, attackers may leave their spawn are [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Escort {
            get {
                return ResourceManager.GetString("Escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People used to believe that witches resided within the forest.
        ///
        ///The forest was a battlefield during the Omnic Crisis..
        /// </summary>
        internal static string Forest {
            get {
                return ResourceManager.GetString("Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Genji {
            get {
                object obj = ResourceManager.GetObject("Genji", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genji flings precise and deadly Shuriken at his targets, and uses his wakizashi to deflect projectiles or delivers a Swift Strike with his technologically-advanced katana that cuts down enemies..
        /// </summary>
        internal static string Genji1 {
            get {
                return ResourceManager.GetString("Genji1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gibraltar {
            get {
                object obj = ResourceManager.GetObject("Gibraltar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Château Guillard is located near Annecy in southeastern France. For hundreds of years, it was the estate of the influential Guillard family, until it gradually fell into disrepair after the family’s power waned in the decades after the Revolution. Recently, the château has found a new owner: the Talon agent Widowmaker, who has returned to her family’s ancestral home..
        /// </summary>
        internal static string Gui8llard {
            get {
                return ResourceManager.GetString("Gui8llard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hanamura {
            get {
                object obj = ResourceManager.GetObject("Hanamura", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanamura is an Assault map in Overwatch.
        ///Hanamura is a well-preserved village of unassuming shops and quiet streets, 
        ///known mostly for its idyllic cherry blossom festival every spring. 
        ///But to those who know its history, Hanamura is the ancestral home of the Shimada ninja clan, 
        ///which had grown over the centuries to become a powerful criminal organization. 
        ///As its neighboring cities expanded, Hanamura was encircled, and eventually it was 
        ///incorporated as a district within a larger city. For now, the i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hanamura1 {
            get {
                return ResourceManager.GetString("Hanamura1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hanzo {
            get {
                object obj = ResourceManager.GetObject("Hanzo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanzo’s versatile arrows can reveal his enemies or fragment to strike multiple targets. 
        ///He can scale walls to fire his bow from on high, or summon a titanic spirit dragon. .
        /// </summary>
        internal static string Hanzo1 {
            get {
                return ResourceManager.GetString("Hanzo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the glitz and glamour of Hollywood, California, where palm trees and fancy cars line the streets, and movie stars, directors, and high-powered studio executives rub shoulders for a chat and a drink at Galand&apos;s. Down the street from the Mandarin Theatre, Goldshire Studios&apos; omnic film auteur, HAL-Fred Glitchbot, has created his two latest films, They Come from Beyond the Moon and Six-Gun Killer, to varying amounts of critical and commercial acclaim. However, even Tinseltown has been gripped by anti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Holly {
            get {
                return ResourceManager.GetString("Holly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hollywood {
            get {
                object obj = ResourceManager.GetObject("Hollywood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Horizon {
            get {
                object obj = ResourceManager.GetObject("Horizon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built as a first step towards humanity&apos;s renewed exploration of space, the Horizon Lunar Colony’s goal was to 
        ///examine the effects of prolonged extraterrestrial habitation—on human and ape alike. The scientists&apos; 
        ///research proved incredibly promising...until, suddenly, all contact and communications with the base were lost..
        /// </summary>
        internal static string Horizon_colony {
            get {
                return ResourceManager.GetString("Horizon_colony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ilios {
            get {
                object obj = ResourceManager.GetObject("Ilios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilios is located in the Aegean sea of Greece, which is part of the Mediterranean Sea.
        ///
        ///Situated atop a small island rising from the Aegean Sea, Ilios is a postcard-perfect Mediterranean town, with a bustling harborside, winding paths for rambling hillside strolls, and gorgeous vistas. It is the ideal vacation stop for people looking for a place to relax, or for those interested in exploring the ruins scattered at the top of the island, where many artifacts and relics of the ancient world have been recentl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ilios2 {
            get {
                return ResourceManager.GetString("Ilios2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia was one of the countries hit hardest by the Omnic Crisis, 
        ///but during the rebuilding process, it rode the wave of the mechanized 
        ///labor industry&apos;s revitalization and entered a period of rapid growth. 
        ///However, after recent attacks from the long-dormant Siberian omnium, 
        ///Russia has returned to war footing, guarding its sparkling cities with 
        ///the massive, human-piloted Svyatogor mechs developed and produced by Volskaya Industries..
        /// </summary>
        internal static string Industries {
            get {
                return ResourceManager.GetString("Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junkertown is an Escort map located in the harsh and unforgiving Australian Outback. 
        ///Constructed from the remains of a destroyed omnium, it&apos;s now the home to a band of 
        ///lawless scavengers known as the Junkers, led by their cutthroat Queen. When they aren’t 
        ///pillaging the omnium&apos;s skeleton for anything of value, the Junkers blow off steam in 
        ///the Scrapyard—a massive gladiatorial arena whose combatants fight for glory, riches...and to survive..
        /// </summary>
        internal static string Junker {
            get {
                return ResourceManager.GetString("Junker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Junkertown {
            get {
                object obj = ResourceManager.GetObject("Junkertown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Junkrat {
            get {
                object obj = ResourceManager.GetObject("Junkrat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junkrat’s area-denying armaments include a Frag Launcher that lobs 
        ///bouncing grenades, Concussion Mines that send enemies flying, and 
        ///Steel Traps that stop foes dead in their tracks..
        /// </summary>
        internal static string Junkrat1 {
            get {
                return ResourceManager.GetString("Junkrat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap King {
            get {
                object obj = ResourceManager.GetObject("King", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King&apos;s Row is an upscale, cosmopolitan neighborhood of London, but just beneath its peaceful surface, tensions between omnics and humans are running high. While much of modern England was built on the backs of omnic laborers, they have been denied the basic rights that humans have, with most omnics forced to live in the dense, claustrophobic city-beneath-the-city known by some as &quot;the Underworld.&quot; Of greater concern is that recent demonstrations by pro-omnic-rights protestors have resulted in violent clashe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kings {
            get {
                return ResourceManager.GetString("Kings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lijiang {
            get {
                object obj = ResourceManager.GetObject("Lijiang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lucio {
            get {
                object obj = ResourceManager.GetObject("Lucio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the battlefield, Lúcio’s cutting-edge Sonic Amplifier buffets 
        ///enemies with projectiles and knocks foes back with blasts of sound. 
        ///His songs can both heal his team or boost their movement speed, and 
        ///he can switch between tracks on the fly. .
        /// </summary>
        internal static string Lucio1 {
            get {
                return ResourceManager.GetString("Lucio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mccree {
            get {
                object obj = ResourceManager.GetObject("Mccree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed with his Peacekeeper revolver, McCree takes out targets with deadeye precision and dives out of danger with eagle-like speed..
        /// </summary>
        internal static string Mccree1 {
            get {
                return ResourceManager.GetString("Mccree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mei {
            get {
                object obj = ResourceManager.GetObject("Mei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mei’s weather-altering devices slow opponents and protect locations. 
        ///Her Endothermic Blaster unleashes damaging icicles and frost streams, 
        ///and she can Cryo-Freeze herself to guard against counterattacks, 
        ///or obstruct the opposing team&apos;s movements with an Ice Wall. .
        /// </summary>
        internal static string Mei1 {
            get {
                return ResourceManager.GetString("Mei1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mercy {
            get {
                object obj = ResourceManager.GetObject("Mercy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercy’s Valkyrie Suit helps keep her close to teammates like a 
        ///guardianangel; healing, resurrecting or strengthening them with 
        ///the beams emanating from her Caduceus Staff. .
        /// </summary>
        internal static string Mercy1 {
            get {
                return ResourceManager.GetString("Mercy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Moira {
            get {
                object obj = ResourceManager.GetObject("Moira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moira’s biotic abilities enable her to contribute healing or damage 
        ///in any crisis. While Biotic Grasp gives Moira short-range options, 
        ///her Biotic Orbs contribute longer-range, hands-off damage and healing; 
        ///she can also Fade to escape groups or remain close to allies in need 
        ///of support. Once she’s charged Coalescence, Moira can save multiple allies 
        ///from elimination at once or finish off weakened enemies. .
        /// </summary>
        internal static string Moira1 {
            get {
                return ResourceManager.GetString("Moira1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Amari has made Necropolis her personal hideout—and an impromptu field base where she can keep an eye on things.
        ///
        ///Head to Ana’s preferred vantage point at the top of the ruins, and use the high ground (and the element of surprise) against the enemy team. Or walk the stone corridors below, and take the fight to them directly—just watch out for pits!.
        /// </summary>
        internal static string Necro {
            get {
                return ResourceManager.GetString("Necro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Necropolis {
            get {
                object obj = ResourceManager.GetObject("Necropolis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nepal {
            get {
                object obj = ResourceManager.GetObject("Nepal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years ago, a group of omnic robots experienced what they described as a spiritual awakening. They abandoned their programmed lives to establish a monastery high in the Himalayas, where like-minded omnics could gather to meditate on the nature of their existence. Led by their spiritual leader, Tekhartha Mondatta, they took over the ruins of an ancient monastery and turned it into the home of the Shambali, a place where omnics and humans alike make pilgrimages in the hopes of finding a greater truth..
        /// </summary>
        internal static string Nepal2 {
            get {
                return ResourceManager.GetString("Nepal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known as the &quot;City of Harmony,&quot; Numbani is one of the few places where omnics and humans live as equals. This collaboration has led to the creation of one of the world&apos;s greatest and most technologically advanced cities in the short time since its establishment after the end of the Omnic Crisis. As part of this year&apos;s Unity Day festivities celebrating the city&apos;s founding, the gauntlet of the infamous Doomfist is being exhibited at the Numbani Heritage Museum..
        /// </summary>
        internal static string Numb {
            get {
                return ResourceManager.GetString("Numb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Numbani {
            get {
                object obj = ResourceManager.GetObject("Numbani", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Oasis {
            get {
                object obj = ResourceManager.GetObject("Oasis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oasis is one of the world&apos;s most advanced cities, a shining jewel rising from the Arabian Desert. A monument to human ingenuity and invention, researchers and academics from around the region came together to found a city dedicated to scientific progress without restraints. The city and its inhabitants are governed by the Ministries, a collection of brilliant minds who possess many secrets that have attracted the interest of powerful organizations from around the world..
        /// </summary>
        internal static string Oasis2 {
            get {
                return ResourceManager.GetString("Oasis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offense heroes possess high mobility and are usually great damage dealers. They are good at scouting, harassment, and pressing objectives. Movement abilities are often associated with offense heroes..
        /// </summary>
        internal static string Offense {
            get {
                return ResourceManager.GetString("Offense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Orisa {
            get {
                object obj = ResourceManager.GetObject("Orisa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orisa serves as the central anchor of her team, and defends her 
        ///teammates from the frontline with a protective barrier. She can 
        ///attack from long range, fortify her own defenses, launch graviton 
        ///charges to slow and move enemies, and deploy a Supercharger to 
        ///boost the damage output of multiple allies at once..
        /// </summary>
        internal static string Orisa1 {
            get {
                return ResourceManager.GetString("Orisa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwatch is a team-based multiplayer online first-person shooter video game developed and published by Blizzard Entertainment.
        ///It was released in May 2016 for Windows, PlayStation 4, and Xbox One. Overwatch assigns players into two teams of six,
        /// with each player selecting from a roster of over 20 characters, known in-game as &quot;heroes&quot;, each with a unique
        /// style of play, whose roles are divided into four general categories: Offense, Defense, Tank, and Support. 
        ///Players on a team work together to secure  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Overwatch_explanation {
            get {
                return ResourceManager.GetString("Overwatch_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwatch features squad-based combat with two 
        ///opposing teams of six players each. Players 
        ///choose one of several hero characters, each
        ///with their own unique abilities and role classes..
        /// </summary>
        internal static string Overwatch_explanation1 {
            get {
                return ResourceManager.GetString("Overwatch_explanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pharah {
            get {
                object obj = ResourceManager.GetObject("Pharah", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soaring through the air in her combat armor, and armed with a launcher that lays down high-explosive rockets, Pharah is a force to be reckoned with.
        ///
        ///.
        /// </summary>
        internal static string Pharah1 {
            get {
                return ResourceManager.GetString("Pharah1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reaper {
            get {
                object obj = ResourceManager.GetObject("Reaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellfire Shotguns, the ghostly ability to become immune to damage, and the power to step
        ///between shadows make Reaper one of the deadliest beings on Earth. .
        /// </summary>
        internal static string Reaper1 {
            get {
                return ResourceManager.GetString("Reaper1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reinhardt {
            get {
                object obj = ResourceManager.GetObject("Reinhardt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clad in powered armor and swinging his hammer, Reinhardt leads a 
        ///rocket-propelled charge across the battleground and defends his 
        ///squadmates with a massive energy barrier..
        /// </summary>
        internal static string Reinhardt1 {
            get {
                return ResourceManager.GetString("Reinhardt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Roadhog {
            get {
                object obj = ResourceManager.GetObject("Roadhog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadhog uses his signature Chain Hook to pull his enemies close before 
        ///shredding them with blasts from his Scrap Gun. He’s hardy enough to 
        ///withstand tremendous damage, and can recover his health with a short breather..
        /// </summary>
        internal static string Roadhog1 {
            get {
                return ResourceManager.GetString("Roadhog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Route66 {
            get {
                object obj = ResourceManager.GetObject("Route66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Soldier76 {
            get {
                object obj = ResourceManager.GetObject("Soldier76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed with cutting-edge weaponry, including an experimental pulse rifle that’s capable of 
        ///firing spirals of high-powered Helix Rockets, Soldier 76 has the speed and support know-how 
        ///of a highly trained warrior. .
        /// </summary>
        internal static string Soldier761 {
            get {
                return ResourceManager.GetString("Soldier761", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sombra {
            get {
                object obj = ResourceManager.GetObject("Sombra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth and debilitating attacks make Sombra a powerful infiltrator. Her hacking can 
        ///disrupt her enemies, ensuring they&apos;re easier to take out, while her EMP provides the 
        ///upper hand against multiple foes at once. Sombra’s ability to Translocate and 
        ///camouflage herself makes her a hard target to pin down..
        /// </summary>
        internal static string Sombra1 {
            get {
                return ResourceManager.GetString("Sombra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support heroes can heal allies, enhance their team&apos;s 
        ///abilities, and debuff enemies. They are poor duelists 
        ///and perform best with their team around them. .
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Symmetra {
            get {
                object obj = ResourceManager.GetObject("Symmetra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetra utilizes her light-bending Photon Projector to dispatch
        ///adversaries, shield her associates, construct teleportation pads 
        ///and deploy particle-blasting Sentry Turrets. .
        /// </summary>
        internal static string Symmetra1 {
            get {
                return ResourceManager.GetString("Symmetra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank heroes have high endurance and excel at protecting allies and disrupting enemies. 
        ///The primary role of the tank is to absorb incoming enemy fire through active abilities 
        ///and a generally high health pool. Secondary to this, soaking the right amount of 
        ///sustainable damage can help team supports farm ultimate charge before an engagement. .
        /// </summary>
        internal static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nestled among the ancient ruins of the Giza Plateau on the outskirts of Cairo, 
        ///the Temple of Anubis is one of many new excavations in the area. 
        ///While most believe that the site is of interest for archaelogical reasons, 
        ///it also hides the entrance to a research facility that extends deep beneath the earth. 
        ///The facility is alleged to house an artificial intelligence, but the whole truth is known 
        ///only to a select few. Not even the agents of Helix Security International who guard the 
        ///facility know wh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Temple {
            get {
                return ResourceManager.GetString("Temple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Torbjorn {
            get {
                object obj = ResourceManager.GetObject("Torbjorn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torbjörn’s extensive arsenal includes a rivet gun and hammer, as well 
        ///as a personal forge that he can use to build upgradeable turrets and 
        ///dole out protective armor packs. .
        /// </summary>
        internal static string Torbjorn1 {
            get {
                return ResourceManager.GetString("Torbjorn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijiang Tower was built in the heart of a modern Chinese metropolis, its busy streets lined with stores, gardens, restaurants, and famous night markets, where foods from around the region are available at all hours. The tower itself is home to one of the leading companies in China&apos;s state-of-the-art space industry, Lucheng Interstellar, an organization with a long pioneering history that is currently pushing the boundaries of space exploration..
        /// </summary>
        internal static string Tower {
            get {
                return ResourceManager.GetString("Tower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tracer {
            get {
                object obj = ResourceManager.GetObject("Tracer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toting twin pulse pistols, energy-based time bombs, and rapid-fire banter, 
        ///Tracer is able to &quot;blink&quot; through space and rewind her personal timeline as 
        ///she battles to right wrongs the world over. .
        /// </summary>
        internal static string Tracer1 {
            get {
                return ResourceManager.GetString("Tracer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Volskaya {
            get {
                object obj = ResourceManager.GetObject("Volskaya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At its height, Overwatch maintained a number of bases around the world, 
        ///each with its own purpose: peacekeeping, scientific research, or in the 
        ///case of Watchpoint: Gibraltar, providing an orbital launch facility. 
        ///The base was mothballed along with the rest of Overwatch&apos;s installations, 
        ///but there have been recent reports of activity within the perimeter. 
        ///Could this indicate the presence of former Overwatch agents, or is this 
        ///the work of organizations with more nefarious intentions?.
        /// </summary>
        internal static string Watchpoint {
            get {
                return ResourceManager.GetString("Watchpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Widowmaker {
            get {
                object obj = ResourceManager.GetObject("Widowmaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widowmaker equips herself with whatever it takes to eliminate her targets, 
        ///including mines that dispense poisonous gas, a visor that grants her squad 
        ///infra-sight, and a powerful sniper rifle that can fire in fully-automatic mode. .
        /// </summary>
        internal static string Widowmaker1 {
            get {
                return ResourceManager.GetString("Widowmaker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Winston {
            get {
                object obj = ResourceManager.GetObject("Winston", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winston wields impressive inventions—a jump pack, electricity-blasting 
        ///Tesla Cannon, portable shield projector and more—with literal gorilla strength. .
        /// </summary>
        internal static string Winston1 {
            get {
                return ResourceManager.GetString("Winston1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zarya {
            get {
                object obj = ResourceManager.GetObject("Zarya", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying powerful personal barriers that convert incoming damage into energy for 
        ///her massive Particle Cannon, Zarya is an invaluable asset on the front lines of any battle. .
        /// </summary>
        internal static string Zarya1 {
            get {
                return ResourceManager.GetString("Zarya1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zenyatta {
            get {
                object obj = ResourceManager.GetObject("Zenyatta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zenyatta calls upon orbs of harmony and discord to heal his 
        ///teammates and weaken his opponents,all while pursuing a 
        ///transcendent state of immunity to damage. .
        /// </summary>
        internal static string Zenyatta1 {
            get {
                return ResourceManager.GetString("Zenyatta1", resourceCulture);
            }
        }
    }
}
